### ISSUE TITLE
Add sql-send-terminator option to example configuration

### ISSUE THREAD

**Issue by ghollisjr** [sebasmonia/datum#12]
For convenience when using the Emacs sql-mode functions like

- `sql-send-string`
- `sql-send-region`
- `sql-send-paragraph`
- `sql-send-buffer`

the `sql-send-terminator` variable can be set to ";;" to match the terminator protocol of datum, but since newcomers might not know this then it might be good to add it to the README examples, e.g.

```
(use-package sql-datum
  :load-path "/path/to/datum/"
  :after sql
  :config
  (add-to-list 'sql-connection-alist
               '("Chinook"
                 (sql-product 'datum)
                 (sql-server "")
                 (sql-user "")
                 (sql-password "")
                 (sql-send-terminator ";;")
                 (sql-datum-options '("--driver" "SQLITE3" ))
                 (sql-database "/path/to/chinook.db"))))
```

Having sql-send-terminator set correctly allows you to use the usual functions and/or keybindings to send queries/regions/buffers to the SQL REPL, so without this it makes datum difficult to use outside of the REPL.

**Comment by sebasmonia** [comment]
First of all, thank you for reporting this! 

I didn't know about this variable, I really need to revisit the internals of `sql-mode`, because the current implementation is a bit lacking (see #9 for example).

Up until now when I used `sql-send-region` I manually added the `;;` terminator.

Will be fixed soon.

**Comment by sebasmonia** [comment]
Documented in 24b2be24e118dc87c59143a02b974f9084c28169.
